services:
  api-service:
    build: 
      context: ./services/api-service
    ports:
      - "8000:8000"
    env_file:
      - ./services/api-service/.env
    depends_on:
      - mongo
    volumes:
      - ./services/api-service/app:/app/src/app # For live-reloading during development
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --reload-dir /app/src/app

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      # These credentials must match the MONGO_URI in the .env file
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example

  ai-service:
    build:
      context: ./services/ai-service
    ports:
      - "8001:8001" # Map the internal port 8001 to your local machine
    volumes:
      - ./services/ai-service/app:/app/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001 --reload --reload-dir /app/app

volumes:
  mongo-data: