version: "3.8"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

  detection:
    build: ./detection-service
    volumes:
      - ./detection-service/videos:/app/videos
    environment:
      KAFKA_BROKER: kafka:9092
    depends_on:
      - kafka

  alert:
    build: ./alert-service
    environment:
      KAFKA_BROKER: kafka:9092
      SMTP_PASSWORD: "6571292c2bf2bb5a83bfb13a0cbec30d"
      RECEIVER_EMAIL: "ngophong1019@gmail.com"
    depends_on:
      - kafka