apiVersion: apps/v1
kind: Deployment
metadata:
  name: drown-detect-deployment
  labels:
    app: drown-detect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drown-detect
  template:
    metadata:
      labels:
        app: drown-detect
    spec:
      containers:
      - name: drown-detect
        image: phongngolam/drown-detect-service:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: drown-detect-service
spec:
  selector:
    app: drown-detect
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: ClusterIP