# Deployment and Service for Drown Detect Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drown-detect-deployment
  labels:
    app: drown-detect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drown-detect
  template:
    metadata:
      labels:
        app: drown-detect
    spec:
      containers:
      - name: drown-detect
        image: phongngolam/drown-detect-service:v1
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: drown-detect-service
spec:
  selector:
    app: drown-detect
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: ClusterIP
---
# Deplotymet and Service for Drown Alert Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drown-alert-deployment
  labels:
    app: drown-alert
  template:
    metadata:
      labels:
        app: drown-alert
    spec:
      replicas: 1
      containers:
      - name: drown-alert
        image: phongngolam/drown-alert-service:v1
        ports:
        - containerPort: 5001
        resources:
          requests:
            memory: "256Mi"
            cpu: "300m"
          limits:
            memory: "1Gi"
            cpu: "600m"
---
apiVersion: v1
kind: Service
metadata:
  name: drown-alert-service
spec:
  selector:
    app: drown-alert
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5001
  type: ClusterIP
