apiVersion: v1
kind: Service
metadata:
  name: {{ include "drown-detect.fullname" . }}
  labels:
    {{- include "drown-detect.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
  selector:
    {{- include "drown-detect.labels" . | nindent 4 }}