apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-kafka
  labels:
    app: {{ .Release.Name }}-kafka
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9092
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}-kafka


# apiVersion: v1
# kind: Service
# metadata:
#   name: {{ include "kafka-chart.fullname" . }}
#   labels:
#     {{- include "kafka-chart.labels" . | nindent 4 }}
# spec:
#   type: {{ .Values.service.type }}
#   ports:
#     - port: {{ .Values.service.port }}
#       targetPort: http
#       protocol: TCP
#       name: http
#   selector:
#     {{- include "kafka-chart.selectorLabels" . | nindent 4 }}
